# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('institute', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('tshirt_size', models.CharField(max_length=1)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong_answer', models.PositiveIntegerField(default=0)),
                ('compile_error', models.PositiveIntegerField(default=0)),
                ('runtime_error', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('institute_rank', models.PositiveIntegerField(default=0)),
                ('user_default_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
