# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160522_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year_joined_institute',
            field=models.CharField(default=2000, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tshirt_size',
            field=models.CharField(max_length=3),
        ),
    ]
