# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20160522_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(default=15, max_length=20),
            preserve_default=False,
        ),
    ]
