# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_userprofile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isstudent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isteacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='students', to='signup.UserProfile'),
        ),
        migrations.AddField(
            model_name='courses',
            name='tas',
            field=models.ManyToManyField(related_name='tas', to='signup.UserProfile'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', to='signup.UserProfile'),
        ),
    ]
