# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_name', models.CharField(max_length=200)),
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong_answer', models.PositiveIntegerField(default=0)),
                ('compile_error', models.PositiveIntegerField(default=0)),
                ('runtime_error', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
